### ISSUE TITLE
[FAQ question] Errors and the location list

### ISSUE THREAD

**Issue by AdrienLemaire** [python-mode/python-mode#1020]
Why are we using the location list to display pep8 errors? 
It took me a while to figure out that the mappings to navigate through errors were `:lne` and `:lp` instead of `:cn` and `:cp`.

I can understand that linting errors are not "errors" per se, but it would be nice to explain this in the manual or FAQ document.

It also makes me wonder about the following: Are there situations where we can have both the quickfix list and location list open?

**Comment by diraol** [comment]
Hum.... sincerely? I have no idea! :p

I'm trying to maintain this project for some time, but I haven't been here since the beginning. So I don't know exactly why this was decided.

Actually, I didn't even knew about these windows differences in vim.

If you think it make sense to be as it is now, and we just miss some documentation, It would be nice if you could send us a Pull Request with a proposal for that. =)

**Comment by lieryan** [comment]
I think displaying pep8 errors makes a lot more sense in location list than in quickfix list. The pep8 checker tool works in a single file and location list is local to a single file so they're already a match; you can have multiple active location lists (one for each window) but you can only have a single quickfix list for the entire vim session.
