### ISSUE TITLE
when completion automatic selection the first one, why?

### ISSUE THREAD

**Issue by smile-kindred** [python-mode/python-mode#1033]

**Comment by reillysiemens** [comment]
@smile-kindred: I had this issue too and was able to resolve it to my satisfaction by following this suggestion from the `:help pymode` documentation.

> Autocompletion is also called by typing a period in Insert mode by default.                                                                                                                   
>                                                                                                                                                                                               
> If there's only one complete item, vim may be inserting it automatically                                                                                                                      
instead of using a popup menu. If the complete item which inserted is not                                                                                                                     
your wanted, you can roll it back use '\<c-w\>' in Insert mode or setup                                                                                                                         
'completeopt' with menuone and noinsert in your vimrc. .e.g.                                                                                                                                  
>                                                                                                                                                                                               
>     set completeopt=menuone,noinsert

**Comment by smile-kindred** [comment]
thanks
