### ISSUE TITLE
Popup help doc

### ISSUE THREAD

**Issue by blayz3r** [python-mode/python-mode#1049]
Been very quiet in here. Anyway, is there any way to customize to the function pymode#doc#find() to use the "new" vim popup feature?

**Comment by diraol** [comment]
Hi @blayz3r can you please take a look at this comment:
https://github.com/python-mode/python-mode/issues/935#issuecomment-554782399

I think this is a very nice way to start moving forward in order to be able to have new features (by the way, I haven't seen anything about vim popup feature until now)

**Comment by blayz3r** [comment]
Ok great thanks!!

**Comment by blayz3r** [comment]
Demo here https://www.reddit.com/r/neovim/comments/b1pctc/float_window_support_with_cocnvim/

**Comment by diraol** [comment]
@blayz3r thanks for the video, very nice feature indeed!
Just one question though. Does vim support it or is it just for neovim?

**Comment by blayz3r** [comment]
Yes it works for both, here is an example https://github.com/mhinz/vim-signify/issues/300

**Comment by blayz3r** [comment]
https://github.com/skywind3000/vim-quickui

**Comment by qazip** [comment]
@blayz3r, do you mind explaining how vim-quickui fixes the issue?

**Comment by blayz3r** [comment]
![image](https://user-images.githubusercontent.com/12205650/81702493-5b0f5680-9439-11ea-922f-9412943d3947.png)

You can install it and use the doc to set up python help in a popup
