### ISSUE TITLE
Invalid Syntax (pyflakes E) Python in Spyder 4.1.2

### ISSUE THREAD

**Issue by BillLe2000** [python-mode/python-mode#1086]
Hello,
I have an invalid syntax (pyflakes E) in my code below. Please see the two link below.  I ran the code and the output was right, but I couldn't understand why my code had an error.  Could anyone know why? Please tell me how to fix it.  Thank you in advance.
![Fig1](https://user-images.githubusercontent.com/39404927/80912861-97d6a180-8d05-11ea-9ceb-9a409be08585.JPG)
![Fig2](https://user-images.githubusercontent.com/39404927/80912877-b50b7000-8d05-11ea-9392-be946854fa62.JPG)
Thank you!
Ben

**Comment by diraol** [comment]
Hi @BillLe2000 from what I could see you are using `Spyder` as IDE right?
Not sure how can we (`python-mode`) help you, since we are a plugin for `Vim`. Are you somehow using `python-mode`?

If not, then you should look for Spyder IDE help, because it seems that your IDE is not effectively showing the errors.

You can take a look in the following issues:

 - https://github.com/spyder-ide/spyder/issues/11154
 - https://github.com/spyder-ide/spyder/issues/11033

Also, you can try running your code through a linter from the command line to have a better controlled output.

**Comment by matias254** [comment]
I am a beginner, I am in a programming course and I downloaded the Spyder, but it turns out that I put
the command "import" and automatically I get that "invalid syntax pyflakes E". If I put the command that I wanted to put completely ("import matplotlib.pyplot as plt;"), then, I also get that invalid syntax pyflakes E. ¿How do I do so that there are no pyflakes or so that I can write calmly?

Don't laugh at me for not knowing anything or for making a mistake about something small. I am literally new to programming and this is my first time doing it.

**Comment by SushmaDasari96** [comment]
> Hello,
> I have an invalid syntax (pyflakes E) in my code below. Please see the two link below. I ran the code and the output was right, but I couldn't understand why my code had an error. Could anyone know why? Please tell me how to fix it. Thank you in advance.
> ![Fig1](https://user-images.githubusercontent.com/39404927/80912861-97d6a180-8d05-11ea-9ceb-9a409be08585.JPG)
> ![Fig2](https://user-images.githubusercontent.com/39404927/80912877-b50b7000-8d05-11ea-9392-be946854fa62.JPG)
> Thank you!
> Ben

Hi,
I have run the code in the Spyder IDE but I did not get any error, I think it's just a bug that comes and goes. anyway, the output is correct,

**Comment by YudiGuzman** [comment]
Hello,
I have an invalid syntax (pyflakes E) in my code below. I think the problem is because of conflict on version package but I am not sure. Could anyone know why? Please tell me how to fix it. Thank you in advance.

import keras
import keras.models import Sequential
import keras.layers import Dense

![Invalid Syntax Pyflakes E](https://user-images.githubusercontent.com/65938408/114348952-e05d2880-9b2c-11eb-8bbb-7edfc01a73e4.png)

**Comment by diraol** [comment]
Hi @YudiGuzman, you are using the wrong syntax. You should do `from ... import ...` Instead of `import ... import ...`

**Comment by YudiGuzman** [comment]
Hi @diraol, Yes. Thank you. I discovered after I sent my problem but not actualized my issue. Sorry. I will be careful about it. Thanks again :)

**Comment by ShauryaS12** [comment]
Hello,
I have an invalid syntax (pyflakes E) in my code below. I don't know why this problem in coming. Could anyone know why? Please tell me how to fix it. Thank you in advance

doom_env = gym.wrappers.Monitor(doom.env, "videos", force = True)


![my problem in ai](https://user-images.githubusercontent.com/83806162/117408219-3efba380-af2d-11eb-8b59-59df03b2e9d2.JPG)

**Comment by OFONITEX** [comment]
print("your name contains " + new_num_char +  " characters".) 
i wrote the above code,and the error was syntax error , it took me about an hour to figure out that my fullstop was outside the quotes. 
so in my own opinion, pyflakes E syntax error actually mean syntax error; you just have to check your code again.

**Comment by luislevill** [comment]
hello
I'm new to this community and I wanted to ask for some help, from now on I apologize for the basics but I just installed zbar and I want to try it with the following code example but that "invalid syntax" appears and I haven't been able to find my mistake

![codigoo](https://user-images.githubusercontent.com/107334270/173213049-f37d227d-6340-4005-be24-be4532381ab4.PNG)

**Comment by luislevill** [comment]
hello
I'm new to this community and I wanted to ask for some help, from now on I apologize for the basics but I just installed zbar and I want to try it with the following code example but that "invalid syntax" appears and I haven't been able to find my mistake

![codigoo](https://user-images.githubusercontent.com/107334270/173213152-63bedca7-2aea-4f3d-8e91-33e21d79a6e5.jpeg)

**Comment by diraol** [comment]
Hi @luislevill.

This is not an issue with `python-mode` (the tool) itself, it is a `python coding problem`, so I'd suggest you to look for help in a more proper place (stackoverflow, python forums, python communities on slack/discord, etc).

If we start handling python coding issues in this issue tracker, other than problems with python-mode itself, we would end up being overloaded with such kind of request.
