### ISSUE TITLE
E837: This Vim cannot execute :py3 after using :python

### ISSUE THREAD

**Issue by mgrabenstein** [python-mode/python-mode#1102]
Latest MacVim update to Custom Version 8.2.1456 (165). started getting these errors.

Error detected while processing CursorMoved Autocommands for "<buffer=1>"..script /<homedir>/.vim/pack/python-mode/start/python-mode/autoload/pymode/lint.vim:
line    1:
E837: This Vim cannot execute :py3 after using :python

Updated my Python-mode to latest, still getting above error.

**Comment by lieryan** [comment]
This is not an issue with python-mode itself, but rather it usually happens if you have other plugins (or some config in your `.vimrc`) that still uses Python 2. Vim can only run Python 2 or Python 3 plugins, but not both simultaneously. python-mode only supports Python 3, so you'll need to disable or update those other plugin if you want to use python-mode or use the `last-py2-support` branch.

Alternatively, if you really, really, really can't live without both plugins, you may want to consider using NeoVim.
