### ISSUE TITLE
E670: Mix of help file encodings within a language

### ISSUE THREAD

**Issue by jfernandz** [python-mode/python-mode#1105]
`vim` is not generating the `pymode` helptag because some encoding problem, I don't know if is this my fault or is caused by some strange character in the `CONTRIBUTORS.txt` file in pylint submodule. :thinking: 

`E670: Mix of help file encodings within a language: /home/wyre/.vim//vim-plug/python-mode/submodules/pylint/CONTRIBUTORS.txt`

**Comment by joejobber** [comment]
Yeah, I am seeing the same. Checking that file shows it is in utf-8 encoding, so not really sure why it causes this error.  Removing the file does not solve anything, because that raises the same error for another file in the pylint module: python-mode/submodules/pylint/tests/functional/n/non_ascii_name.txt

**Comment by joejobber** [comment]
Here's a temporary solution:
- go to .vim/pack/third-party/start/python-mode/submodules/pylint/ (or your equivalent)
- move the ./tests dir to a temporary location
- move the CONTRIBUTORS.txt file to a temporary location
- run helptags
- copy the dir and file back
