### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by ShantelWilson** [python-mode/python-mode#1112]
Hi, I am a beginner in Python and I am having an indentation error with my code in VSCode. I tried several times to make sure my indentations are the same but it's not working.

```
import random

def UserInput(prompt):
	
	while True:
			try:
				return int(input(prompt))
			except:
				print('You did not enter a correct value.')



def main():
		# TODO - allow default values
		lowest = UserInput('Pick lowest numberL: ')
		# TODO - make sure highest is now lower then lowest 
		highest = UserInput('Pick highest number: ')
		randomNumber = random.randint(lowest, highest) 
		
		Number1 = None
		count = 1
		while Number1 != randomNumber:
	    Number1 = UserInput('Pick your number ')
		else:
      print('Your number was ', Number1)
		  count += 1
      print(count)

if __name__ == '__main__':
	  main()


Here is the error:

```
File "main.py", line 26
    Number1 = UserInput('Pick your number ')
                                           ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by diraol** [comment]
Hi @ShantelWilson first of all, welcome!

As a first tip, for python specific doubts and questions I'd suggest you ask in a more proper forum, such as [Stackoverflow](stackoverflow.com/). you will find better answers and much faster than here.

Also, this issue tracker is aimed at python-mode plugin questions.

Anyway, python is a language that consider the source code identation. In your case, you have identation errors. In order to ease  your coding, try to setup your IDE with spaces instead of tabs, I have a feeling that you are not seeing the errors because of your editor hiding it with wrong identations.

Take a look at your code, the `Number 1 = UserInput('...` line is wrongly aligned.

**Comment by ShantelWilson** [comment]
> Hi @ShantelWilson first of all, welcome!
> 
> As a first tip, for python specific doubts and questions I'd suggest you ask in a more proper forum, such as [Stackoverflow](stackoverflow.com/). you will find better answers and much faster than here.
> 
> Also, this issue tracker is aimed at python-mode plugin questions.
> 
> Anyway, python is a language that consider the source code identation. In your case, you have identation errors. In order to ease your coding, try to setup your IDE with spaces instead of tabs, I have a feeling that you are not seeing the errors because of your editor hiding it with wrong identations.
> 
> Take a look at your code, the `Number 1 = UserInput('...` line is wrongly aligned.

Thank you! I fixed it and it works now.
