### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by ryanyeah** [python-mode/python-mode#387]
Honestly, don't know why you guys have gotta make this so hard to install. Following your "recommended" install using pathogen, I have failed to get it working. I copy exactly what is in that box to my .vimrc (after git cloning) and it gives an error (mainly due to the first line have a single quotation mark on it - which i have no idea if that is intentional or not). I tried several variations of taking the quotation mark out etc to no avail. I also pointed directly to debug.vim to try and open it to no avail. 

I then gave up and tried to install via a debian package. add-apt-respository has a dependency for that to be installed (not mentioned), so I googled that and installed that package, only to find that bash still doesn't recognise "add-apt-repository". I give up. 

Also you don't even list how to enable your software on the main github page nor if I click README.rst file (which seems to link to same thing). I need to go hunting around in your docs folder to find this. 

I don't see why I need to be l33t to be able to run this. It would be rad if you could touch up on the docs to help out new users. 
##

**Comment by JokerQyou** [comment]
I understand his complains, as the documentation did not point out all the details we need to know when we go into trouble.
I too tried this thing today and end up with a lot of `invalid expression` errors upon the first start. Turns out to be the line ending in DOS format (`^M` appears with errors), so I used `dos2unix` to convert all the files to Unix style line endings and the errors are gone now.
I did tried to follow the trouble shooting instructions, but where is this `debug.vim` file? You told us to look for `<path_to_pymode>/debug.vim`, which is suppose to be `<path_to_python-mode>/debug.vim`, many people might misunderstand it and try to look for `debug.vim` inside the `pymode` folder.
