### ISSUE TITLE
Difference between `git clone` and debian `apt-get` from repo installs of vim-python-mode

### ISSUE THREAD

**Issue by Cbhihe** [python-mode/python-mode#586]
Just installed _`python-mode`_ for vim via git.
Have never used (g)it before.  Am new to all this.

In retrospect I came to wonder whether there are any differences in the installed versions of the python-mode plug-in via:
**a)** either using pathogen.vim

```
$ git clone git://github.com/klen/python-mode.git
```

**b)** or for Debian based Lx distros

```
$ sudo add-apt-repository [repo] && sudo apt-get update

$ sudo apt-get install vim-python-mode
```

Is it possible to add a comment to the install steps to that effect ? 

Is there an easier (automated) update path for future versions ?  [git || repo] 

Thanks. -ced
##

**Comment by HuStmpHrrr** [comment]
personally i think they are the same.

it's just salt from different brands, so the taste will just keep as salty as salt should be.

but if you use `apt-get`, you have to wait for them to update the deb. that's kind of downside if you want to always keep yourself up to date(which actually is not a brilliant idea since the latest one is not the best for most of the time).

i prefer `git` way because i simply have more control over the version i am using. you can 
```
git checkout tag|branch
```
very easily if you have the repo too.

if you are in the type of being not aware of the details of your tools and just expecting them to work, probably `apt-get` way is much more preferable.

**Comment by Cbhihe** [comment]
@HuStmpHrrr: Sorry for the delay in responding and thank you for your reply. You answered my question perfectly. 
I **am** the type of person who, the very first day, will take his tools apart and ask "why" and "how" at every turn. However I am new to git and I have to do my work too, so I will stick to the `$ sudo apt-get install ...` route as long as it is available. I don't mind not working with the most recent build  of python-mode. It is not an issue for what I do.
-ced

**Comment by sumit2840** [comment]
In many situation the "apt-get install" provides an alternative way in the installing of any package if the "git clone" throws any ERROR and the all goes vice-versa.
"E 28: no disk space left "is such a situation where the git clone come under no use there u can try the api-get install medium.
