### ISSUE TITLE
Missing python3 Errors syntax highlight

### ISSUE THREAD

**Issue by PhML** [python-mode/python-mode#691]
Those errors are not in the syntax file:

```
 'BlockingIOError',
 'BrokenPipeError',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'FileExistsError',
 'FileNotFoundError',
 'InterruptedError',
 'IsADirectoryError',
 'NotADirectoryError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ResourceWarning',
 'StopAsyncIteration',
 'TimeoutError'
```

Those errors are in the syntax file but no more in python3:

```
 'StandardError',
 'VMSError',
```

Since the syntax file seems to be common to python 2 and 3, I don't know if I should add the missing ones and delete others or just add the missing ones.

**Comment by brycepg** [comment]
For anyone else looking at this, the relevant file is `syntax/python.vim`

I think it would be better to just add the missing ones. And not delete the old ones.

That's how the vim runtime syntax/python.vim does it. There's no reliable way to check if the code is Python 2 or Python 3. Let the linter pick up on errors since it runs against a specific python version.
