### ISSUE TITLE
python-mode very slow after update

### ISSUE THREAD

**Issue by weatherfrog** [python-mode/python-mode#701]
Hi,
After reinstalling vim and upgrading pymode to the latest version (cloned the repo), vim has become painfully slow. When editing a .py file, pressing tab or entering insert mode takes 1-3 seconds. It's impossible to get any work done. When I remove pymode, everything's back to normal.
I'm using Ubuntu 16.04, vim 7.4.1689, Python 3.5.2.
Is anyone having similar issues?

**Comment by timofurrer** [comment]
I've got the exact same issue. `python-mode` is unusable for me because it's that slow ..

**Comment by ns-cweber** [comment]
I just started using pymode, and it's slow for me too. Opening Python files takes ~2 seconds compared to ~100ms for other files.

**Comment by jones77** [comment]
Same here.  Undo takes a second or two ...

**Comment by diraol** [comment]
Hi @ns-cweber and @jones77, 
the slowed opening is probably due to the folding feature, that we already know that has several issues. So, disabling it will improve A LOT the performance while opening python files. You guys can try other vim plugins specifically for the folding feature while our is not fixed (contributions are very welcome!).

Regarding the content of the original message, which is not related to "opening the file", it may have something to do with the autocomplete feature, and it will depend on other plugins too, not necessarily python-mode.

Previously I was using Youcompleteme, and it was dam slow. I've just switched it for another and the performance increased a lot.

Take a look at our documentation (or some of the opened issues regarding **fold** to see how to disable it and also to get suggestions regarding alternatives for folding).

**Comment by diraol** [comment]
By the way, I'm going to close this issue since it is from 2016 and we have changed completely the project from that point to now and the focus of the issue probably was already fixed (and the following messages are not related to the same issue).

I'm doing this just for organization purposes (we have newer issues with more specific details and alternatives/solutions). An issue with "this is just slow" isn't that much helpful for none of us.

But if there is still problems going on, please, do not hesitate to comment on other issues or open new ones if there isn't an opened issue about the desired topic.
