### ISSUE TITLE
pymode folding incorrect when comment is not indented

### ISSUE THREAD

**Issue by teto** [python-mode/python-mode#702]
I often have code like this,

```
class Toto:
    def setObjective(self,obj):
# print("inspect,",inspect.getmodule(obj))
        # print("inspect,",inspect.getmodule(obj) in sp)
        if self.is_sympy(obj):
            obj = self.sp_to_pulp(obj)

```

which with pymode_fold = 1 doesn't fold correctly because it's apparently based on indentation, which in the previous snippet is broken by the comment. Isn't it possible to fix this ? How does pymode work ? it's not in the :help .

**Comment by fmv1992** [comment]
This does not happen to me. The folding works good in this case probably because of other settings somewhere.

Anyways try:
`
setlocal foldignore?
`
You should get:
`
foldignore=#  
`
That's vim default. It will ignore the indent if it contains a "#".
Thus setting foldignore to nothing probably will solve the issue:
`
setlocal foldignore=
`
