### ISSUE TITLE
pymode lint checkers list is not used

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [python-mode/python-mode#713]
When I have the following list of lint checkers:

    let g:pymode_lint_checkers = ['pyflakes', 'pep8', 'pep257']

I only get pyflakes warnings. But when I save the same code, with:

    let g:pymode_lint_checkers = ['pep8', 'pep257']

I suddenly get the warnings from pep8 and pep257.

So the other entries in the list besides pyflakes are simply ignored. Then the list does not make sense.

**Comment by MadWombat** [comment]
I cannot seem to be able to reproduce this. I get errors from every linter I have configured. Can you try this with `vim -u debug.vim`?

**Comment by pwl07** [comment]
hello, same issue here, I have in .vimrc 
let g:pymode_lint = 1
let g:pymode_lint_checker = ['pylint']
but getting errors from pyflake only 
$PATH/test.py |15 col 11 error| invalid syntax [pyflakes]

tried even with vim -u ~/.vim/bundle/python-mode/debug.vim test.py
but still getting only pyflake

**Comment by smheidrich** [comment]
I'm having the same issue. Trying to bisect it, I found that everything still works fine in a8b1fe6887fa3ac875524ce907c4c6396135deb5, then from a52c4620ed2355b33de9699f162ef2da57d92fce to 70d6bf598d5f0f2070003bc36a9a8d2a7cce8eb0 linting is just totally broken, and finally d2dead6ce9d900b26dbf1a06c52969f4194eda64 fixes linting in general but ignores ``g:pymode_lint_checkers``. Considering that this issue was filed before the commit that started giving me issues, I guess this is effectively a new issue, but the symptoms are the same so I'm reporting it here.

Can anyone reproduce this or is it just me?

**Comment by fmv1992** [comment]
I believe this issue was solved in a recent commit.

Let me know if it still persists!

Feel free to reopen the issue.
