### ISSUE TITLE
Folding seems to crash Vim when used with Gdiff from fugitive

### ISSUE THREAD

**Issue by kylemacfarlane** [python-mode/python-mode#740]
Vim 8 on Windows 10. When I call :Gdiff on python files Vim locks up. It seems that the culprit is python-mode getting stuck in a loop at the following:

```
line 2:     while getline(fs) !~ s:def_regex && getline(fs) !~ s:doc_begin_regex
line 3:         let fs = nextnonblank(fs + 1)
line 4:     endwhile
line 2:     while getline(fs) !~ s:def_regex && getline(fs) !~ s:doc_begin_regex
line 3:         let fs = nextnonblank(fs + 1)
line 4:     endwhile
line 2:     while getline(fs) !~ s:def_regex && getline(fs) !~ s:doc_begin_regex
line 3:         let fs = nextnonblank(fs + 1)
line 4:     endwhile
```

And so on. 200k lines of that are logged in the two seconds it takes me to close Vim.

**Comment by andrewebdev** [comment]
I can confirm that this happens on `Ubuntu 17.04 in NVIM (NeoVim) v0.2.1-dev` as well.
Gdiff crashes on python files, but if I remove python-mode then Gdiff runs perfectly fine

**Comment by fmv1992** [comment]
Can you please provide more information? What is Gdiff?

Please give us full access to reproduce (and thus tackle the issue). Post an example of source code as well.

Also check out our new debugging method: https://github.com/python-mode/python-mode#troubleshootingdebugging

**Comment by andrewebdev** [comment]
Sorry, should have been clearer.

`Gdiff` is one of the `vim-fugitive` commands/functions.

**Comment by fmv1992** [comment]
@andrewebdev,

Due to the myriad of combinations between vim plugins we cannot account for
their interaction, unless there is something very obvious to it like a clash in
global variables (which should never happen if you use vim's standards).

Nevertheless I encourage you to try our debugging procedure (limited to
python-mode only):

`vim -i NONE -u <path_to_pymode>/debugvimrc.vim` then submit your debug file,
most likely at: `/tmp/pymode_debug_file.txt` (appears with `:messages`).

***Do check for sensitive information in the file before submitting.***

No hurry for submitting it :)

**Comment by andrewebdev** [comment]
Right the issue seems to have been resolved. I updated all my plugins (and neovim) before looking into this issue again. Doesn't seem to exist anymore.

@kylemacfarlane is this now resolved for you as well?
