### ISSUE TITLE
Rope completion auto select the last entry!

### ISSUE THREAD

**Issue by kierun** [python-mode/python-mode#748]
When I have autocompletion enabled, the selection is always the last entry which get pasted after the `.`. This is *never* what I want. Could I have the list of possible choices but no automatic picking the last one from the list?

For example, typing `self.` automatically get converted to `self.__subclasshook__` which is clearly utterly useless as I have to delete it before I can start typing the first letters of what I want. Then, it appears just fine.

Any idea?

**Comment by akahanaton** [comment]
I got the same problem, any help on this? thank you guys so much

**Comment by kierun** [comment]
Kinda. I removed `neomake` and `deoplete` from the list of plugins I was loading and the problem went away. However, I find that I am missing some features of both so it's not ideal.

☹

**Comment by akahanaton** [comment]
I disabled the dot completion in pymode crudely by editing: python-mode/plugin/pymode.vim
call pymode#default('g:pymode_rope_complete_on_dot', 0)
because setting the "pymode_rope_complete_on_dot" in my .vimrc file as
let g:pymode_rope_complete_on_dot = 0
can't prevent the the dot completion.
then I use YouCompleteMe for code completion.....

**Comment by kierun** [comment]
Is there a fix?…

**Comment by fmv1992** [comment]
I have not fiddled with rope in this project so far... Have you @diraol ?

Fixes are welcome by anyone ; )

**Comment by kierun** [comment]
Installing deoplete and deoplete-clang2 does make the problem appear. Sadly, I need those for C++ code.

**Comment by benwad** [comment]
I've been having this issue as well with the latest neovim/deoplete/pymode.

**Comment by diraol** [comment]
Hi all,

I haven't dealt with rope yet.

It may need some kind of configuration for `rope` plugin that we are not using.

Actually, I think we really need to move `rope` source code away from our repo and start using it as a submodule, such as how we have done with `pylint`, `pydocstyle` and so on.
Our `rope` copy may be really old now, and eventually this problem have already been solved on the newer versions.

I am somewhat without free time because of my work, so I don't know when I am going to have some time to do this "migration". Being so, any kind of help from the community would be more than welcome! =)

**Comment by rzk** [comment]
Same problem here with neovim and python-mode, __subclasshook__ is inserted as first suggestion.
