### ISSUE TITLE
Disable "show documentation" take no effect 

### ISSUE THREAD

**Issue by spybdai** [python-mode/python-mode#757]
description:
    add the following 2 lines in .vimrc to disable "show documentation" feature, but it doesn't work at all:
   
    let g:pymode_doc = 0
    let g:pymode_doc_bind = ''

**Comment by jennaliu** [comment]
How do you expect it to work?

**Comment by spybdai** [comment]
If I am right, if we disable this feature with mentioned configuration, press 'K' will NOT jump to another window to show the docs. But now, it does.

Or talk with another way, there is no difference whether if we config this or not.

shouldn't this be an issue?

**Comment by jennaliu** [comment]
If you press K in a barebone Vim, it opens the corresponding man page in another window. This is the default behavior of Vim. Python-mode simply  remapped K to another command that opens the documentation in a preview window. The reason you are seeing python documentation instead of man page is that it also replaced man with pydoc elsewhere. I agree that it is not very intuitive when I didn't know K's default mapping.

**Comment by spybdai** [comment]
Thanks @jennaliu 

do u know how to map the go_to_definition key to Ctrl+Enter?

I just use:

let g:pymode_rope_goto_definition_bind = '<C-Enter>'

but it doesn't work.

**Comment by jennaliu** [comment]
<C-CR> is Ctrl+Enter, but it seems like Vim cannot map a combination of two special keys.
