### ISSUE TITLE
Project Maintenance Inquiry

### ISSUE THREAD

**Issue by AdibMurshed** [python-mode/python-mode#804]
Hello @python-mode !
I am Adib Murshed, the President of the Iniftar Foundations at: [http://www.blog.iniftar.com](http://www.blog.iniftar.com). I would like to claim this project to continue its development, open-source and non-profit.

**Comment by fmv1992** [comment]
Adib, anyone can "claim" this project as it is licensed under LGPL.

Just hit fork and go head, the sky is the limit.

Inquiry resolved.

**Comment by diraol** [comment]
@fmv1992 I think that @AdibMurshed was talking about taking the lead of the project, since it looks like you and @klen isn't being able to have much time to maintain the project (review/accept PRs, deal with issues, maintain the project updated, etc).

Off course they can just fork the project for themselves, but that may not reflect the benefits for every user of python-mode, that is already spread as a dependency on many other projects.

I really think that the open source community can benefit a lot from such support, **if** the **community** agrees that _iniftar Foundation_ can lead this project.

But, as far as I've seen, this project is not lead by a community but by you and @klen, which make this yours own decision.

Just to make it clear, I'm not suggesting that the ownership of python-mode should be transfered to _iniftar Foundation_, but I think that, if they show enought responsibility and prior open source collaboration to help maintaining this project, they would be added to the project 'team' with permission to accept PRs.

Moreover, some well defined criteria on how to accept PRs, make releases and stuff like that would help also.

Just saying....

**Comment by diraol** [comment]
Ow, and I'm not defending that they should gain responsibility on the project, I think that it should be evaluated.

**Comment by fmv1992** [comment]
@diraol,

I think I have misunderstood the claimer objective.

I totally agree. I'm interested in having this project led by community and towards community.

I've been hesitant to push my own improvements to the project here:

https://github.com/fmv1992/python-mode

Basically I have removed the hard dependency on files from projects and added those as submodules (with symlinks to relevant files; the benfits is that there is no need for maintenance and updates from our part). I have implemented some minor improvements as well.

Maybe it is time to push them here and see how it goes... However a `git submodule update --init --recursive` would be required. Do you think this would cause much hassle to other users?

I think that we are also lacking some sort of testing. Again I'm hesitant to merge PR due to the lack of tests (and this is one of vim's shortcomings; there is no official test procedures beyond simple assertions).

Having said all that, I'm willing to give permissions to other users that contribute more than occasionaly to this project.

Those ideas are open for feedback! I do want to see this project alive again.

**Comment by fmv1992** [comment]
Actually let's make this a wider issue. We can start with a topic, let it mature for a couple of days (that is give the community some time to give input) then take a bigger step towards guidelines.

Link here: https://github.com/python-mode/python-mode/issues/805

**Comment by AdibMurshed** [comment]
@diraol That matches exactly with my intentions, pretty much. @fmv1992 The Iniftar Foundations is claiming ownership of abandoned and unwanted projects to continue their development (open-source, non-profit and active).

**Comment by fmv1992** [comment]
@adibmurshed,

Exactly what you mean but not exactly what you've written.

I encourage you to look up the meaning of the word "claim" as well of
"abandoned", "inactive" and specially "unwanted".

But I encourage you even further to collaborate to this project. When doing so
rather than "claiming" things we might merrily add you to the contributors
list.

I will not further respond to this thread and I hope to stumble upon a
constructive contribution/feedback from you in this project.

Best,

**Comment by axsuul** [comment]
@fmv1992 @AdibMurshed has commented on many GitHub projects proposing ownership which leads to me believe that his intentions are nefarious:

https://github.com/backup/backup/issues/803
https://github.com/GabiAxel/ng-polymer-elements/issues/65
https://github.com/pickhardt/maintainers-wanted/issues/25
https://github.com/berekuk/Ubic/issues/86

**Comment by fmv1992** [comment]
The less attention we give to those guys the better.

This issue is not even worth commenting.

**Comment by ms-ati** [comment]
Cannot agree @fmv1992 - should be highlighted also to Github as potential abuse and start getting more eyes and minds working on ways to detect and head off these sorts of actions before they improve their sales pitch
