### ISSUE TITLE
g:python_run possible bug

### ISSUE THREAD

**Issue by alphaCTzo7G** [python-mode/python-mode#812]
By design, If you define 

`let g:python_run=0`

in your .vimrc, you wont be able to run python source code directly in the python window.

While your vim is loaded with the default .vimrc (with `let g:python_run=0`), and if you attempt to change the variable to `g:python_ru=1,` in the ex mode, the variable does change to g:python=1.

However, if you try to run Python code from the VIM window, it wont work. If  you save the .vimrc with 

`let g:python_run=1`,

and try

`:so ~/.vimrc`

to load the .vimrc again, it doesn't work either.

The only way is to redefine `g:python_run` in your .vimrc, get out of your current vim session, and restart vim.

I would expect that if you reload your .vimrc file or redefine `g:python_run`, it should work.

**Comment by fmv1992** [comment]
This is not a bug.

Actually there is no `g:python_run` but **`g:pymode_`**`run`.

And due to vim's design you cannot load the same file twice (or something like
it). Try to put an `echom '@@@ loaded'` before:

~~~~~~
" Run python code
if g:pymode_run
~~~~~~

then load your vim.

You'll see that it gets echoed once but if you
`source /xxx/python-mode/ftplugin/python/pymode.vim` again it does not. It is intended
vim behavior.
