### ISSUE TITLE
centos; vim7.4; vundle install python-mode; insert mode; cursor jump anywhere

### ISSUE THREAD

**Issue by woisnow** [python-mode/python-mode#832]
centos; vim7.4; vundle install python-mode; insert mode; cursor jump anywhere; when i edit or use "blackspace" del, the cursor jump anywhere, why?

**Comment by fmv1992** [comment]
Hey @woisnow,

Thanks for your update on this bug. I know this is a bit of a hassle but can you please submit the output of your bug report as suggested in our [troubleshooting session](https://github.com/python-mode/python-mode#troubleshootingdebugging)?

We had a similar issue in the past due to the folding function  moving around the cursor. By using the aforementioned bug reporting procedure we will be able to check if you have the latest commit from `develop` branch.

**Comment by woisnow** [comment]
This issue is similar to #815 , i solved this problem by setting "let g:pymode_folding = 0", but i lost the "folding func" ,  so i write my own "folding func" instead of the python-mode's. Thank you!
