### ISSUE TITLE
Strange test suite behaviour

### ISSUE THREAD

**Issue by diraol** [python-mode/python-mode#849]
I've made a PR (#846) and the tests seems to be broken.

Running them locally (`./test.sh`) I've noticed that the `folding3` test take a long time to run and also that it sometimes fail and some times succeed.

Most of the times the error I've seen is:
`rm: não foi possível remover '/tmp/pymode_disposable.py': Arquivo ou diretório não encontrado`
`rm: it was not possible to remove '/tmp/pymode_disposable.py': File or directory not found`
I've tried to take a look at the tests, but I couldn't find what may be breaking the tests "randomly".

Any suggestions on how to proceed?

**Comment by fmv1992** [comment]
@diraol,

Thanks for taking your time to inspect this part of the code.

I'm starting to write the tests for this plugin. The test structure is quite complicated but it somehow works except for that part.

The folding 3 file should:

    " Test that doing (reversible) changes in insert mode or normal mode to a
    " buffer do not alter their folding.

and it should help us ensuring that our folding is robust. I wrote some helper functions that emulate users input.

I'm also aware that it sometime works.

I'll disable for now but I think it is important to have this running in order to help our folding being more stable.

**Comment by fmv1992** [comment]
temporarily fixed with f0b58fae1debec65d45a51715c6aa96214a88490.
