### ISSUE TITLE
python mode reporting sytaxError on print

### ISSUE THREAD

**Issue by ustcyue** [python-mode/python-mode#882]
I am using python 2.7. but somehow it reports error on python2.7 print 

![image](https://user-images.githubusercontent.com/2103334/39247325-a5a7b1ee-48cb-11e8-88f6-1f0ff2598de5.png)

**Comment by diraol** [comment]
Hi @ustcyue can you provide us more information?

Please, follow the [Troubleshooting/Debugging](https://github.com/python-mode/python-mode#troubleshootingdebugging) session ;)

**Comment by BTrey** [comment]
I'm not the original submitter but I'm seeing the same thing.  pymode_python is set to 'python3' and the first print statement gives a syntax error because of the lack of parenthesis.  pymode_python does not appear anywhere in my .vimrc file, nor can I find anywhere else that it is being manually set.  Additionally, neither manually setting it to 'python2' nor unletting it changes the behavior - print still generates a syntax error.  This was not happening until I did a git pull this morning, and I have not changed .vimrc or other vim configuration.

[pymode_debug_file.txt](https://github.com/python-mode/python-mode/files/1977673/pymode_debug_file.txt)

**Comment by exajuk** [comment]
I have the same issue ("Invalid syntax error" for a python2-style `print`). Adding `let g:pymode_python = 'python'` in .vimrc actually avoids the error:
```
[Pymode] Code checking is completed. No errors found.
```
 but causes **a lot** of other errors during vim startup (and various commands), e. g.:
```
Error detected while processing function pymode#init:
line    2:
E319: Sorry, the command is not available in this version: python import sys, vim
line    3:
E319: Sorry, the command is not available in this version: python sys.path.insert(0, vim.eval('a:plugin_root'))
```
Any suggestions? Does python-mode still support python2 linting?

**Comment by diraol** [comment]
Closing the issue because of inactivity.

But I would recommend taking a look in the python version that vim was built with (`vim --version`)and the current running python version (in vim) (`python3 import sys; print(sys.version_info)` or `python import sys; print(sys.version_info)`)
