### ISSUE TITLE
Python Mode automatically enables :set number

### ISSUE THREAD

**Issue by DarrienG** [python-mode/python-mode#907]
Why?

**Comment by alphaCTzo7G** [comment]
Seems like this happens here: https://github.com/python-mode/python-mode/blob/7611a8cf2c17bac330afdedf28f8d305e14a9bc4/ftplugin/python/pymode.vim#L70

Do you have `let g:pymode_options` on?

**Comment by fmv1992** [comment]
also I think the idea is that this plugin does what is most useful for a broad range of developers

the defaults should be sane defaults which are good for most situations and they should be "disablable"

as such I think most developers use numbers by default

let them express here if they don't

**Comment by DarrienG** [comment]
Hell, while we're at it, let's set `ttyfast` and `scrolljump=-50`, let's just import my `vimrc` and go from there!

I disagree. Extensions should be small, and stay within their scope. Doing things like enabling line number is ridiculous.

**Comment by alphaCTzo7G** [comment]
The point of this plugin is to make it easier for developers get the most `sensible` settings so that they can start coding as quickly as possible. From what I have seen most VIM users do prefer `number` or `relativenumber`. However, I haven't seen too many people talk about `ttyfast` or `scrolljump`, as it helps a lot in navigating buffers..

If we are aiming to make this plugin as a single plugin that sets the best defaults for python programming.. I think it is a good idea to have numbers on by default. 

Most modern editors do make these choices for users by default.. but also allow users the ability to turn it off if they choose to..

**Comment by DarrienG** [comment]
I don't agree. If you're using Vim, chances are that you already have a customized setup. You aren't jumping straight into Python using Vim.

I personally stopped using this plugin after about an hour because it overrode my own config (line numbers being the most notable immediately). I think making the assumption that people want a plugin to take over their editor and override their config is a bad assumption.

But what do I know? To you I'm a random guy on the internet talking about a Vim plugin he used for an hour.
