### ISSUE TITLE
Update pylama to latest version to fix Python 3.7 compatibility

### ISSUE THREAD

**Issue by ghost** [python-mode/python-mode#933]
Current `pylama` would generate errors with Python 3.7. It seems that the latest `pylama` has fixed this. Please update the `pylama` submodule to the latest version.

**Comment by diraol** [comment]
I don't think the latest pylama will fix the problems we are facing with python 3.7, but it was updated anyway. =)

**Comment by benjamingorman** [comment]
The latest pylama seems to have some python3-incompatible code such as this:

`if options.async and 'pylint' in options.linters:`
(since async is now a keyword)

Due to this problem with Pylama several features of python-mode such as `:PymodeLint` won't currently work on Python 3.7+.

So I hope that #934 proceeds to replace Pylama, else perhaps we can submit a patch to Pylama to fix the broken syntax.
