### ISSUE TITLE
Interactive Python

### ISSUE THREAD

**Issue by linux2coder** [python-mode/python-mode#956]
I would like to know , is there any possibility to run python in **interactive mode** inside vim instead of a screen to display outputs

**Comment by lieryan** [comment]
This seems to be outside the scope of python-mode, but if you use the llatest vim/nvim, there's `:term`/`:terminal`, which opens a shell command and allows you to interact with it interactively. You can also specify another command to run instead of your regular shell, e.g. `:term ./manage.py shell`.

**Comment by diraol** [comment]
@linux2coder `:term ipython` solves it for you?

**Comment by linux2coder** [comment]
Thanks for your help guys , :term ipython -i  filename.py and :term python -i filename.py 
works for me

**Comment by linux2coder** [comment]
Is there a way to show the terminal output in vertical split screen (right side ) in vim?

**Comment by dsabsay** [comment]
@linux2coder `:vert ter` opens a terminal window as a vertical split.
