### ISSUE TITLE
README.md : add 'yes' or 'no' for installation using Vundle

### ISSUE THREAD

**Issue by WaterSibilantFalling** [python-mode/python-mode#981]
I use Vundle to install plugins and, like others, I have used Vundle to install python-mode.

Now that I have errors and pymode isn't working, I am wondering if using Vundle was, somehow, responsible as Vundle is not listed as a method for installing python-mode. 

The issue is that a 'yes' or 'no' statement should be added to the READEME.md regarding installation of python-mode via Vundle.

**Comment by diraol** [comment]
Hi @AbsurdMagpieScrutinies !

I've just tested, in a clean environment, and `Vundle` seems to clone `python-mode` correctly, including the submodules.
And I just followed Vundle default instructions, without any kind of modifications or hacks.
By using:
`Plugin 'python-mode/python-mode'` I was able to get python-mode correctly installed.

So I think we can add it to our Readme.md (Would you do it?)

**Comment by sleepyhollo** [comment]
I am having trouble installing python-mode with Vundle. Vundle also didnt work with `klen/python-mode`.

windows 10 64 bit
Vim 8.1; patches 1-1583

---

I managed to get python-mode to work; but now I am getting stuck on #972. I reinstalled git to allow symlinks and stared using vim-plug instead of vundle.
