### ISSUE TITLE
Init rope project is frozing my vim

### ISSUE THREAD

**Issue by Migacz85** [python-mode/python-mode#995]
I'm having this output on the bottom of the vim:
`
"Coding/www/4Project/run.py" 430L, 16148C written        
[Pymode] Init Rope project: /home/migacz 
`

**Comment by diraol** [comment]
Hi @Migacz85, you can both disable the Rope functionality from python-mode (add `let g:pymode_rope = 0` to your `.vimrc`) or avoid opening any python file while being in your home folder. If you have rope enabled and you open a python file while being in your home folder, python-mode and rope will understand that you are in a python project and will try to evaluate everything under that directory as a python project. As you are in your home folder, the number of files and dirs are quite big, which will make Rope take some time to evaluate everything (It does not freeze, it is just evaluating all files under your home directory).

**Comment by diraol** [comment]
In your case, I would `cd` into `/home/migacz/Coding/www/4Project` and then open `vim run.py`. It will be much much faster for sure.

**Comment by Migacz85** [comment]
I just disabled it. Ok great so I see that the problem would be solved if I will just change path inside vim. 
You have maybe some line that I can put to my .vimrc that will change it automaticly each time I will open a new file/buffer ?

**Comment by diraol** [comment]
@Migacz85 I'm not sure if this make much sense. I mean, Rope evaluate a project (not a single file), in order to be able to provide auto complete, refactoring and other features. If it changes the "path" for every open file/buffer, it would not consider the "full project path". I think..... lol

Take a look at the Rope documentation, both [here (python-mode docs)](https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L397-L613) and in [Rope project documentation](https://github.com/python-rope/rope/blob/master/docs/overview.rst). This may make things more clear.

But we're open for suggestions and contributions! If you have any idea about how we can improve `python-mode` please, let us know - or even better, send us a Pull Request! =)

**Comment by zgpio** [comment]
@diraol  Why not implement pymode to automatically understand the project root directory? 
Sometimes I forget to switch to the project directory.

**Comment by diraol** [comment]
That's the point @zgpio, defining which is the project root directory is not a trivial task.

It is already done, up to some point, considering VCS directories.
But going further than that can be very tricky.

Also, I may be saying something wrong, but It may have an assumption that I think was made when the plugin was built that is: You are going to work in one specific project at a time (vim session).

Which means, among other things, that it won't handle multiple contexts at the same time. So, keeping the project context into the path that vim was firstly initiated *or* into the "closest VCS repo" is the easiest and fastest way to go.

I'm not sure if this is done by python-mode or rope.
It would require some investigation.

If you are interested in doing such investigation and propose a change, be welcome! I can't help much with that for now.

**Comment by trysten** [comment]
I've forgotten this quirk a couple times. It might be a good idea (at least for me) to display the path being parsed so one can detect an improper project root.

My issue stems from starting netrw with `vim .` in parent directories and forgetting to set vim's working directory with `:cd`
