### ISSUE TITLE
aM motion does not select decoraters

### ISSUE THREAD

**Issue by Zarathustra2** [python-mode/python-mode#996]
Consider the following function:

```python
@a_decorator
def test(self):
     print("Not selecting decorator")
 ```

When I use **vaM** everything excluding the decorator gets selected. Imo a decorator belongs to a method and should be selected as well.

**Comment by diraol** [comment]
Just adding here a sample python script with a more complete alternatives (function and method with decorator) for us to test this possible improvement:

```python
def a_decorator(func)
    print("chamando func")
    f = func()
    print("Pós func")
    return f


@a_decorator
def teste():
    print("Not Selecting Decorator")


Class Teste:
    @a_decorator
    def metodo(self):
        print("Meu método")


teste()

testinho = Teste()
testinho.metodo()
```

**Comment by diraol** [comment]
Hi @Zarathustra2 thanks for the issue! =)

Your suggestion indeed make sense.
In order to be able to do this, we need to improve the regex used to do the selection over here:
https://github.com/python-mode/python-mode/blob/develop/after/ftplugin/python.vim#L40-L42

I'm with limited time to dedicate to the project, specially improvements (I'm trying to handle more critical issues, specially #935, #977 and #932), so, contributions in form of Pull Requests are very welcome!

**Comment by Zarathustra2** [comment]
Then we would also have to rework this: [https://github.com/python-mode/python-mode/blob/develop/autoload/pymode/motion.vim#L50](https://github.com/python-mode/python-mode/blob/develop/autoload/pymode/motion.vim#L50)

Since we just increment the line by 1 if we want to select the inner function this would fail if we adjust the regex to catch also decorators. (=btw the increment of 1 would fail to select the right starting line if the parameters are on multiple lines, but tbh how often do you have a method with that many parameters?)

Maybe I find some time to try something out but this is the first time working with advandced regex expressions and vimscript.

**Comment by diraol** [comment]
Hi @Zarathustra2 I'm not exactly an experienced or expert dev in vimscript too.... I'm just trying to do the best that I can to maintain this project alive ;)
So, I'll review everything to my best, but there is always a chance of problems and new bugs. So, let's learn together by doing it! :laughing:

**Comment by KamranMaharov** [comment]
Hi @diraol . @Zarathustra2 , thank you for opening this issue. I also recently became fond of pymode, and decided to contribute as much as i can. I agree with you that solely changing regexp definition will not help. It requires refactoring in vimscript as well.
https://github.com/python-mode/python-mode/blob/7a449a5ee505bbabf4d16ad78ce67a087840d2e9/autoload/pymode/motion.vim#L71
https://github.com/python-mode/python-mode/blob/7a449a5ee505bbabf4d16ad78ce67a087840d2e9/autoload/pymode/motion.vim#L76
At least these lines require attention, because first one stops searching backwards when it encounters the line of which first character is not whitespace.
If our cursor is at anywhere in ABC, search will end at @dec2. :( But it should go up until @dec1.
```
@dec1
@dec2
ABC
```
Second one seems to skip decorator lines entirely. :(

Are you guys fine with keeping existing key mapping and adding decorator motion on top of them? Like,
**aM** will select everything except decorators, **iM** will select everything under _def_, and something like **dM** will choose everything including decorators.
Kind of, **dM** > **aM** > **iM**.

**Comment by KamranMaharov** [comment]
And also what do you think of this approach?
_pymode#motion#select(first_pattern, second_pattern, inner)_
first_pattern would be "@", second_pattern would be "def" for functions.
first_pattern would be "class", second_pattern would also be "class" for classes.

from current cursor position, _pymode#motion#select_ will go up until last first_pattern (in the search direction), then from that point, will go down until first second_pattern (again in the search direction), then do selection based on _inner_. we should change inner as well from boolean variable to ternary.

That way, we also keep backward compatibility.
@diraol , please let me know if it sounds reasonable.
Thank you.

**Comment by KamranMaharov** [comment]
Hi @diraol @Zarathustra2 , i made a PR for this issue, if you don't mind.
Tested with the above script which @diraol posted (thank you). Everything works fine.
aM - includes decorator part as well, if it exists.
iM/iC - is backward compatible, still chooses inner part of the method and class.
for aM/aC, behavior slightly changes to not include all the blank lines following method/class definition while selecting.
